sofficePath: /Applications/LibreOffice.app/Contents/MacOS/soffice
htmltopdfPath: docker run --rm -v /data/pdfs:/converted/ --add-host devt.ala.org.au:192.168.65.2 arachnysdocker/athenapdf athenapdf --delay=10000
#sofficePath: /usr/bin/soffice
storageDir: /data/pdfs

server:
  type: simple
#  rootPath: /api
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 9090

logging:
  level: "INFO"
  loggers:
    "io.dropwizard": "INFO"
    "au.org.ala": "DEBUG"
    "metrics": "OFF"
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout

metrics:
  frequency: 30 minutes
  reporters:
    - type: log
      logger: metrics
      markerName: marker

httpClient:
    timeout: 5 minutes