sofficePath: /usr/bin/soffice
htmltopdfPath: /usr/bin/wkhtmltopdf
storageDir: /storage/pdfs

server:
  type: simple
#  rootPath: /api
  applicationContextPath: /api
  adminContextPath: /admin
  connector:
    type: http
    port: 9090

logging:
  level: "INFO"
  loggers:
    "io.dropwizard": "INFO"
    "au.org.ala": "DEBUG"
    "metrics": "OFF"
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout

metrics:
  frequency: 30 minutes
  reporters:
    - type: log
      logger: metrics
      markerName: marker

httpClient:
    timeout: 5 minutes